@startuml

left to right direction

actor User
actor System

package "Irrigation" {
  User --> (Add parcel)
  User --> (Add culture)
  User --> (Add hygrometer device)
  User --> (Add valve device)
  User --> (Measurement history overview)
  User --> (Manual irrigation)
  System --> (Automatic irrigation)
}

@enduml