substitutions:
  sensor_name: "esp1"
  ip_subaddress: "121"

esphome:
  name: esp-sensor
  friendly_name: "Sensor ${sensor_name}"

esp32:
  board: esp32dev

logger:
  level: INFO

api:

ota:
  platform: esphome
  password: "!32ESP_OTA_Password"

wifi:
  ssid: "Bafarica"
  password: "!bafi123"
  manual_ip:
    static_ip: 192.168.100.${ip_subaddress}
    gateway: 192.168.100.1
    subnet: 255.255.255.0
  ap:
    ssid: "esp_sensor_setup"
    password: "12345678"

captive_portal:

mqtt:
  broker: 192.168.100.10
  port: 1883
  username: ""
  password: ""
  topic_prefix: "sensors/${sensor_name}"

sensor:
  - platform: adc
    pin: GPIO36
    name: "Soil Moisture Sensor"
    id: moisture_sensor
    unit_of_measurement: "%"
    update_interval: 10s
    attenuation: 11db
    filters:
      - calibrate_linear:
          - 2.7 -> 0     # prilagodi prema stvarnim oÄitanjima
          - 1.1 -> 100
      - clamp:
          min_value: 0
          max_value: 100
    on_value:
      then:
        - mqtt.publish:
            topic: "sensors/${sensor_name}/data"
            payload: !lambda |-
              char buf[80];
              snprintf(buf, sizeof(buf),
                       "{\"type\":\"HUMIDITY\",\"measuredValue\":%.1f}",
                       x);
              return std::string(buf).c_str();

binary_sensor:
  - platform: status
    name: "ESP Sensor Status"
