esphome:
  name: esp-sensor

esp32:
  board: esp32dev

ota:
  platform: esphome
  password: "!32ESP_OTA_Password"

logger:

api:

wifi:
  ssid: "Bafarica"
  password: "!bafi123"

  manual_ip:
    static_ip: 192.168.100.122
    gateway: 192.168.100.1
    subnet: 255.255.255.0

  ap:
    ssid: "esp_sensor_setup"
    password: "12345678"

captive_portal:

mqtt:
  broker: 192.168.100.10  # IP adresa MQTT brokera (tvoj backend)
  port: 1883
  username: ""           # Ako koristiš autentifikaciju, upiši korisničko ime
  password: ""           # Ako koristiš autentifikaciju, upiši lozinku
  topic_prefix: "sensors/esp-sensor"  # Prefiks topic-a, možeš prilagoditi

globals:
  - id: moisture
    type: float
    restore_value: no
    initial_value: '50.0'

interval:
  - interval: 10s
    then:
      - lambda: |-
          float value = 30.0 + (rand() % 40);  // Simulira vlagu 30–69%
          id(moisture) = value;
          ESP_LOGI("sensor", "Simulated moisture: %.1f%%", value);
      - mqtt.publish:
          topic: sensors/esp-sensor/data
          payload: !lambda |-
            char buffer[100];
            snprintf(buffer, sizeof(buffer),
                     "{\"sensorName\":\"ESP2\",\"type\":\"HUMIDITY\",\"measuredValue\":%.1f}",
                     id(moisture));
            return std::string(buffer).c_str();
     
