esphome:
  name: esp-sensor

esp32:
  board: esp32dev

logger:

api:

wifi:
  ssid: "Bafarica"
  password: "!bafi123"

  manual_ip:
    static_ip: 192.168.1.123
    gateway: 192.168.1.1
    subnet: 255.255.255.0

  ap:
    ssid: "esp_sensor_setup"
    password: "12345678"

captive_portal:

http_request:
  verify_ssl: false

interval:
  - interval: 10s
    then:
      - http_request.post:
          url: http://192.168.100.11:8080/measurements/from-esp
          request_headers:
            Content-Type: application/json
          json:
            sensorName: ESP1
            type: HUMIDITY
            measuredValue: "1"


