esphome:
  name: esp-sensor

esp32:
  board: esp32dev

logger:

api:

wifi:
  ssid: "Bafarica"
  password: "!bafi123"

  manual_ip:
    static_ip: 192.168.100.123
    gateway: 192.168.100.1
    subnet: 255.255.255.0

  ap:
    ssid: "esp_sensor_setup"
    password: "12345678"

captive_portal:

http_request:
  verify_ssl: false

globals:
  - id: moisture
    type: float
    restore_value: no
    initial_value: '50.0'

interval:
  - interval: 10s
    then:
      - lambda: |-
          float value = 30.0 + (rand() % 40);  // Simulira vlagu 30–69%
          id(moisture) = value;
          ESP_LOGI("sensor", "Simulated moisture: %.1f%%", value);
      - http_request.post:
          url: http://192.168.100.11:8080/measurements/from-esp
          request_headers:
            Content-Type: application/json
          body: !lambda |-
            char buffer[100];
            snprintf(buffer, sizeof(buffer),
                     "{\"sensorName\":\"ESP1\",\"type\":\"HUMIDITY\",\"measuredValue\":%.1f}",
                     id(moisture));
            return std::string(buffer);
