substitutions:
  device_name: "esp1"
  ip_subaddress: "131"

esphome:
  name: esp-valve
  friendly_name: Valve

esp32:
  board: esp32dev

logger:

api:

ota:
  platform: esphome
  password: "!32ESP_OTA_Password"

wifi:
  ssid: "Bafarica"
  password: "!bafi123"
  manual_ip:
    static_ip: 192.168.100.${ip_subaddress}
    gateway: 192.168.100.1
    subnet: 255.255.255.0

mqtt:
  broker: 192.168.100.10
  port: 1883
  username: ""
  password: ""
  discovery: false
  topic_prefix: valve/${device_name}

output:
  - platform: gpio
    pin: GPIO2
    id: valve_led

switch:
  - platform: output
    name: "Valve Control"
    id: valve_control
    output: valve_led
    retain: true

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO19

font:
  - file: "arial.ttf"
    id: my_font
    size: 40

display:
  - platform: st7789v
    model: "TTGO TDisplay 135x240"
    cs_pin: GPIO5
    dc_pin: GPIO16
    reset_pin: GPIO23
    backlight_pin: GPIO4
    rotation: 90
    width: 135
    height: 240
    offset_height: 52
    update_interval: 500ms
    lambda: |-
      it.fill(Color(0, 0, 0));
      if (id(valve_control).state) {
        it.print(10, 30, id(my_font), Color(0, 255, 0), "Valve: ON");
      } else {
        it.print(10, 30, id(my_font), Color(255, 0, 0), "Valve: OFF");
      }







   


